title = "Aktion Kinderhilfe Münster e.V."
theme = 'hugo-universal-theme'
languageCode = "de"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "de"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false


[menu]

# Main menu
[[menu.main]]
    name       = "Startseite"
    identifier = "menu.Startseite"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Mehr erfahren"
    identifier = "mehr"
    url        = "/mehr/"
    weight     = 2

[[menu.main]]
    name       = "Förder-Mitglied werden"
    identifier = "foerder"
    url        = "/foerder/"
    weight     = 3

[[menu.main]]
    name       = "Einmalig spenden"
    identifier = "menu.spenden"
    url        = "/spenden/"
    weight     = 4

[[menu.main]]
    name       = "Verein & Stiftung"
    identifier = "menu.vereinstiftung"
    url        = "/vereinstiftung/"
    weight     = 5


[[menu.main]]
    identifier = "contact"
    name       = "Kontakt"
    url        = "/contact/"
    weight     = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+49 170 38 71 876"
    pre = "<i class='fas fa-2x fa-phone'></i>"

    
[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:peter@kinderhilfe-ms.de"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params]

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    about_us = "<p>Hilfe zur Selbsthilfe durch solidarisches Miteinander weltweit.</p>"
    copyright = "© 2016 Aktion Kinderhilfe Münster e.V."

    disabled_logo = true
    logo_text = "Aktion Kinderhilfe Münster e.V."

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Aktion Kinderhilfe Münster e.V.</strong>
        <br>Von-Kluck-Straße 14-16
        <br>48151 Münster
        <br>
      </p>
      """
      
    
[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Hilfe zur Selbsthilfe durch solidarisches Miteinander weltweit</p>
      </p>
      """

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.recent_posts]
    enable = true
    title = "Aktuelles"
    subtitle = "...Wir sind dabei unsere Webseite zu überarbeiten und bitten um etwas Geduld..."
    hide_summary = false

[params.footer.recent_posts]
    enable = false
